service: spike-lambda-container-image

frameworkVersion: "2"

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: ap-northeast-1
  lambdaHashingVersion: 20201221

functions:
  hello:
    image: "607754652120.dkr.ecr.ap-northeast-1.amazonaws.com/lambda-python@sha256:88d67e38978cfc5da0693897172e05dceb13ede6148dba1e8958a9e1b56c9436"
